// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/acya-skulskaya/go-musthave-diploma/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepositoryInterface creates a new instance of MockOrderRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepositoryInterface {
	mock := &MockOrderRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepositoryInterface is an autogenerated mock type for the OrderRepositoryInterface type
type MockOrderRepositoryInterface struct {
	mock.Mock
}

type MockOrderRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepositoryInterface) EXPECT() *MockOrderRepositoryInterface_Expecter {
	return &MockOrderRepositoryInterface_Expecter{mock: &_m.Mock}
}

// AllByUser provides a mock function for the type MockOrderRepositoryInterface
func (_mock *MockOrderRepositoryInterface) AllByUser(ctx context.Context, userID uint) ([]models.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AllByUser")
	}

	var r0 []models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]models.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []models.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepositoryInterface_AllByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllByUser'
type MockOrderRepositoryInterface_AllByUser_Call struct {
	*mock.Call
}

// AllByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockOrderRepositoryInterface_Expecter) AllByUser(ctx interface{}, userID interface{}) *MockOrderRepositoryInterface_AllByUser_Call {
	return &MockOrderRepositoryInterface_AllByUser_Call{Call: _e.mock.On("AllByUser", ctx, userID)}
}

func (_c *MockOrderRepositoryInterface_AllByUser_Call) Run(run func(ctx context.Context, userID uint)) *MockOrderRepositoryInterface_AllByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_AllByUser_Call) Return(orders []models.Order, err error) *MockOrderRepositoryInterface_AllByUser_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepositoryInterface_AllByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]models.Order, error)) *MockOrderRepositoryInterface_AllByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOrderRepositoryInterface
func (_mock *MockOrderRepositoryInterface) Create(ctx context.Context, userID uint, orderNumber string) (models.Order, error) {
	ret := _mock.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) (models.Order, error)); ok {
		return returnFunc(ctx, userID, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string) models.Order); ok {
		r0 = returnFunc(ctx, userID, orderNumber)
	} else {
		r0 = ret.Get(0).(models.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = returnFunc(ctx, userID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - orderNumber string
func (_e *MockOrderRepositoryInterface_Expecter) Create(ctx interface{}, userID interface{}, orderNumber interface{}) *MockOrderRepositoryInterface_Create_Call {
	return &MockOrderRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, userID, orderNumber)}
}

func (_c *MockOrderRepositoryInterface_Create_Call) Run(run func(ctx context.Context, userID uint, orderNumber string)) *MockOrderRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_Create_Call) Return(order models.Order, err error) *MockOrderRepositoryInterface_Create_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, userID uint, orderNumber string) (models.Order, error)) *MockOrderRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function for the type MockOrderRepositoryInterface
func (_mock *MockOrderRepositoryInterface) Finish(ctx context.Context, orderNumber string, status string, accrual float64, userID uint) error {
	ret := _mock.Called(ctx, orderNumber, status, accrual, userID)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64, uint) error); ok {
		r0 = returnFunc(ctx, orderNumber, status, accrual, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepositoryInterface_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockOrderRepositoryInterface_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
//   - status string
//   - accrual float64
//   - userID uint
func (_e *MockOrderRepositoryInterface_Expecter) Finish(ctx interface{}, orderNumber interface{}, status interface{}, accrual interface{}, userID interface{}) *MockOrderRepositoryInterface_Finish_Call {
	return &MockOrderRepositoryInterface_Finish_Call{Call: _e.mock.On("Finish", ctx, orderNumber, status, accrual, userID)}
}

func (_c *MockOrderRepositoryInterface_Finish_Call) Run(run func(ctx context.Context, orderNumber string, status string, accrual float64, userID uint)) *MockOrderRepositoryInterface_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 uint
		if args[4] != nil {
			arg4 = args[4].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_Finish_Call) Return(err error) *MockOrderRepositoryInterface_Finish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepositoryInterface_Finish_Call) RunAndReturn(run func(ctx context.Context, orderNumber string, status string, accrual float64, userID uint) error) *MockOrderRepositoryInterface_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessed provides a mock function for the type MockOrderRepositoryInterface
func (_mock *MockOrderRepositoryInterface) GetUnprocessed(ctx context.Context, limit uint) ([]models.Order, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessed")
	}

	var r0 []models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]models.Order, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []models.Order); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepositoryInterface_GetUnprocessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessed'
type MockOrderRepositoryInterface_GetUnprocessed_Call struct {
	*mock.Call
}

// GetUnprocessed is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint
func (_e *MockOrderRepositoryInterface_Expecter) GetUnprocessed(ctx interface{}, limit interface{}) *MockOrderRepositoryInterface_GetUnprocessed_Call {
	return &MockOrderRepositoryInterface_GetUnprocessed_Call{Call: _e.mock.On("GetUnprocessed", ctx, limit)}
}

func (_c *MockOrderRepositoryInterface_GetUnprocessed_Call) Run(run func(ctx context.Context, limit uint)) *MockOrderRepositoryInterface_GetUnprocessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_GetUnprocessed_Call) Return(orders []models.Order, err error) *MockOrderRepositoryInterface_GetUnprocessed_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepositoryInterface_GetUnprocessed_Call) RunAndReturn(run func(ctx context.Context, limit uint) ([]models.Order, error)) *MockOrderRepositoryInterface_GetUnprocessed_Call {
	_c.Call.Return(run)
	return _c
}

// Show provides a mock function for the type MockOrderRepositoryInterface
func (_mock *MockOrderRepositoryInterface) Show(ctx context.Context, orderNumber string) (models.Order, error) {
	ret := _mock.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for Show")
	}

	var r0 models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Order, error)); ok {
		return returnFunc(ctx, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Order); ok {
		r0 = returnFunc(ctx, orderNumber)
	} else {
		r0 = ret.Get(0).(models.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepositoryInterface_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type MockOrderRepositoryInterface_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockOrderRepositoryInterface_Expecter) Show(ctx interface{}, orderNumber interface{}) *MockOrderRepositoryInterface_Show_Call {
	return &MockOrderRepositoryInterface_Show_Call{Call: _e.mock.On("Show", ctx, orderNumber)}
}

func (_c *MockOrderRepositoryInterface_Show_Call) Run(run func(ctx context.Context, orderNumber string)) *MockOrderRepositoryInterface_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_Show_Call) Return(order models.Order, err error) *MockOrderRepositoryInterface_Show_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepositoryInterface_Show_Call) RunAndReturn(run func(ctx context.Context, orderNumber string) (models.Order, error)) *MockOrderRepositoryInterface_Show_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockOrderRepositoryInterface
func (_mock *MockOrderRepositoryInterface) UpdateOrderStatus(ctx context.Context, orderNumber string, status string) error {
	ret := _mock.Called(ctx, orderNumber, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orderNumber, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepositoryInterface_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderRepositoryInterface_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
//   - status string
func (_e *MockOrderRepositoryInterface_Expecter) UpdateOrderStatus(ctx interface{}, orderNumber interface{}, status interface{}) *MockOrderRepositoryInterface_UpdateOrderStatus_Call {
	return &MockOrderRepositoryInterface_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderNumber, status)}
}

func (_c *MockOrderRepositoryInterface_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderNumber string, status string)) *MockOrderRepositoryInterface_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepositoryInterface_UpdateOrderStatus_Call) Return(err error) *MockOrderRepositoryInterface_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepositoryInterface_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, orderNumber string, status string) error) *MockOrderRepositoryInterface_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}
