// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/acya-skulskaya/go-musthave-diploma/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceRepositoryInterface creates a new instance of MockBalanceRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepositoryInterface {
	mock := &MockBalanceRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceRepositoryInterface is an autogenerated mock type for the BalanceRepositoryInterface type
type MockBalanceRepositoryInterface struct {
	mock.Mock
}

type MockBalanceRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepositoryInterface) EXPECT() *MockBalanceRepositoryInterface_Expecter {
	return &MockBalanceRepositoryInterface_Expecter{mock: &_m.Mock}
}

// GetByUser provides a mock function for the type MockBalanceRepositoryInterface
func (_mock *MockBalanceRepositoryInterface) GetByUser(ctx context.Context, userID uint) (models.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 models.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (models.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) models.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.UserBalance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepositoryInterface_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockBalanceRepositoryInterface_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockBalanceRepositoryInterface_Expecter) GetByUser(ctx interface{}, userID interface{}) *MockBalanceRepositoryInterface_GetByUser_Call {
	return &MockBalanceRepositoryInterface_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID)}
}

func (_c *MockBalanceRepositoryInterface_GetByUser_Call) Run(run func(ctx context.Context, userID uint)) *MockBalanceRepositoryInterface_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepositoryInterface_GetByUser_Call) Return(userBalance models.UserBalance, err error) *MockBalanceRepositoryInterface_GetByUser_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *MockBalanceRepositoryInterface_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) (models.UserBalance, error)) *MockBalanceRepositoryInterface_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalsByUser provides a mock function for the type MockBalanceRepositoryInterface
func (_mock *MockBalanceRepositoryInterface) GetWithdrawalsByUser(ctx context.Context, userID uint) ([]models.UserBalanceFlow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsByUser")
	}

	var r0 []models.UserBalanceFlow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]models.UserBalanceFlow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []models.UserBalanceFlow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserBalanceFlow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsByUser'
type MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call struct {
	*mock.Call
}

// GetWithdrawalsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockBalanceRepositoryInterface_Expecter) GetWithdrawalsByUser(ctx interface{}, userID interface{}) *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call {
	return &MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call{Call: _e.mock.On("GetWithdrawalsByUser", ctx, userID)}
}

func (_c *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call) Run(run func(ctx context.Context, userID uint)) *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call) Return(userBalanceFlows []models.UserBalanceFlow, err error) *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call {
	_c.Call.Return(userBalanceFlows, err)
	return _c
}

func (_c *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]models.UserBalanceFlow, error)) *MockBalanceRepositoryInterface_GetWithdrawalsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockBalanceRepositoryInterface
func (_mock *MockBalanceRepositoryInterface) Withdraw(ctx context.Context, userID uint, orderNumber string, sum float64) error {
	ret := _mock.Called(ctx, userID, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, float64) error); ok {
		r0 = returnFunc(ctx, userID, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceRepositoryInterface_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBalanceRepositoryInterface_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - orderNumber string
//   - sum float64
func (_e *MockBalanceRepositoryInterface_Expecter) Withdraw(ctx interface{}, userID interface{}, orderNumber interface{}, sum interface{}) *MockBalanceRepositoryInterface_Withdraw_Call {
	return &MockBalanceRepositoryInterface_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, orderNumber, sum)}
}

func (_c *MockBalanceRepositoryInterface_Withdraw_Call) Run(run func(ctx context.Context, userID uint, orderNumber string, sum float64)) *MockBalanceRepositoryInterface_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBalanceRepositoryInterface_Withdraw_Call) Return(err error) *MockBalanceRepositoryInterface_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceRepositoryInterface_Withdraw_Call) RunAndReturn(run func(ctx context.Context, userID uint, orderNumber string, sum float64) error) *MockBalanceRepositoryInterface_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
